name: Generate random failure
on: push
jobs:
  randomly-failing-job:
    runs-on: ubuntu-latest
    steps:
      - name: Generate 0 or 1
        id: generate_number
        run: echo "random_number=$(($RANDOM % 2))" >> $GITHUB_OUTPUT

      - name: Pass or fail
        run: |
          echo "valor é ${{ steps.generate_number.outputs.random_number }}"