name: Publish to TestPyPI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/bpmn_parser/
    permissions:
      id-token: write
    steps:

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1