name: Publish to TestPyPI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/bpmn_parser/
    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Setup Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest

    - name: Install dependencies
      run: make install

    - name: Bump version
      run: |
        poetry version patch

        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add pyproject.toml
        git commit -m "Bump version to $(poetry version -s)"
        git tag v$(poetry version -s)

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        tags: true

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: v$(poetry version -s)
        name: Release v$(poetry version -s)
        body: |
          ## Changes
          - Bumped version to $(poetry version -s)
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build package
      run: poetry build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1