name: Tests and Linting

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  python:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Setup Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest

    - name: Install dependencies
      run: make install

    - name: Run linting check
      run: make check_lint

    - name: Run formatting check
      run: make check_format

    - name: Run types check
      run: make check_types

    - name: Run tests
      run: make tests

    - name: Update coverage badge if necessary
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Updated coverage badge
        file_pattern: 'assets/coverage-badge.svg'
